### ISSUE TITLE
Pattern matching & JVM bytecode verification error

### ISSUE THREAD

**Issue by azagniotov** [lmcgrath/scotch-lang#13]
When trying to compile the following code with `scotch -m leet204`

```
module leet204

primesLessThan limit = take (iterate (\x -> x + 1) 1) limit

take [] limit = []
take _ 0 = []
take (x:xs) limit = x:take xs (limit - 1)
iterate fn int = int:iterate fn (fn int)
main = primesLessThan 100
```

The following JVM exception has occurred:
https://gist.github.com/azagniotov/311379f9d866027a3fcd

Outputting the byte code:

```
> scotch -m leet204 -o .
> javap -p -v leet204/\$\$Module.class > module.txt
```

Shows this byte code:
https://gist.github.com/azagniotov/44a31fd3113754494826

**Comment by lmcgrath** [comment]
Yes! I just ran into this myself.

There's a short term workaround, however. If you order your pattern cases differently, it'll run:

```
take _ 0 = []
take (x:xs) limit = x:take xs (limit - 1)
take [] limit = []
```
